// Prüfung der Seite im echten Browser: P2 lädt ohne Fehler, Werkzeug vor Text; P3 Lesen am gezeichneten Instrument (0,5 mA) trifft;
// P4 Kurve 0 … 1 mA: größte Abweichung ≤ 20 µA; P5 Bildsatz: Browser ≤ 20 µA gegen Prüfstrom, alle gültig; P6 Dokumentation vorhanden.
import { createRequire } from 'node:module';
import fs from 'node:fs';
const require = createRequire(import.meta.url);
const { chromium } = require('/tmp/node_modules/playwright');
const H = '/workspace/Analoganzeige_lesen/Seite/'; const V = fs.readFileSync(H + 'VERSION', 'utf8').trim();
const S = '/tmp/claude-1000/-workspace/905236e7-aea4-4c03-805a-5e5668f5230d/scratchpad/';
let fehler = 0; const BEF = []; const sage = (gut, t) => { console.log(`  ${gut ? 'ok    ' : 'FEHLER'} ${t}`); BEF.push({ gut, text: t }); if (!gut) fehler++; };
const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 1400, height: 1000 } });
const konsole = []; p.on('pageerror', e => konsole.push(e.message)); p.on('console', m => { if (m.type() === 'error') konsole.push(m.text()); });
await p.goto(`file://${H}Analoganzeige_lesen_${V}.html`, { waitUntil: 'load', timeout: 180000 }); await p.waitForTimeout(1500);
sage(konsole.length === 0, 'keine Konsolenfehler' + (konsole.length ? ': ' + konsole[0].slice(0, 120) : ''));
const lage = await p.evaluate(() => document.getElementById('lesen').getBoundingClientRect().top);
sage(lage < 900, `Werkzeug vor Text: Knopf „Lesen“ bei ${lage.toFixed(0)} px`);
const e1 = await p.evaluate(() => { const e = window.LABOR.letzt.e; return { wert: e.wert, gueltig: e.gueltig, striche: e.striche.striche.length, haupt: e.striche.haupt.length, punkte: e.zeiger ? e.zeiger.n : 0 }; });
sage(e1.gueltig && Math.abs(e1.wert - 0.5) < 0.02, `gezeichnetes Instrument bei 0,50 mA: gelesen ${e1.wert === null ? '—' : e1.wert.toFixed(3)} mA, ${e1.striche}/${e1.haupt} Striche, ${e1.punkte} Zeigerpunkte, gültig ${e1.gueltig}`);
await p.screenshot({ path: S + 'analog_seite.png' });
await p.click('#kurve'); await p.waitForFunction(() => window.LABOR.kurveErgebnis, null, { timeout: 120000 });
const k = await p.evaluate(() => window.LABOR.kurveErgebnis); const abwK = k.map(q => q.wert === null ? 1 : Math.abs(q.wert - q.strom)); const mxK = Math.max(...abwK);
sage(mxK <= 0.02 && k.every(q => q.gueltig), `Kurve 0 … 1 mA: ${k.length} Punkte, größte Abweichung ${(mxK * 1000).toFixed(1)} µA, gültig ${k.filter(q => q.gueltig).length}`);
await p.click('#satzKnopf'); await p.waitForFunction(() => window.LABOR.satzErgebnis, null, { timeout: 180000 });
const s = await p.evaluate(() => window.LABOR.satzErgebnis); const abwS = s.map(z => Math.abs(z.js - z.soll)); const mxS = Math.max(...abwS);
sage(mxS <= 0.02 && s.every(z => z.gueltig), `Bildsatz vom Gerät: ${s.length} Bilder, größte Abweichung Browser ${(mxS * 1000).toFixed(1)} µA, gültig ${s.filter(z => z.gueltig).length}`);
await p.evaluate(() => window.scrollTo(0, document.querySelector('#satz').getBoundingClientRect().top + window.scrollY - 200)); await p.waitForTimeout(300); await p.screenshot({ path: S + 'analog_satz.png' });
const doku = (await p.evaluate(() => document.body.textContent)).replace(/\s+/g, ' ');
sage(doku.includes('Der Skalenbogen') && doku.includes('Die Zeigergerade') && doku.includes('Modbus TCP') && doku.includes('Ablesung am Schnittpunkt'), 'Dokumentation in der Seite: Bogen, Zeigergerade, Schnittpunkt, Modbus');
const kopf = await p.$eval('#fassung', e => e.textContent); sage(kopf.includes(`Fassung ${V}`) && kopf.includes('Ralph Wystup'), `Kopf: ${kopf.slice(0, 60)}`);
await b.close();
fs.writeFileSync(H + 'pruefe_seite.json', JSON.stringify({ datum: new Date().toISOString(), fassung: V, befunde: BEF, fehler }, null, 1));
console.log(fehler ? `${fehler} Beanstandung(en)` : 'alles in Ordnung'); process.exit(fehler ? 1 : 0);
